-- LernBuddy Database Schema
-- Last Updated: 2026-02-14
-- Purpose: Tracking unique user installs and parent feedback.

-- 1. Table for unique user tracking
-- This helps us count how many individual browsers have installed/started the app.
CREATE TABLE IF NOT EXISTS public.unique_users (
    id UUID PRIMARY KEY, -- Generated on the client and stored in localStorage
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    user_agent TEXT,
    locale TEXT
);

-- 2. Table for parent feedback
-- Stores feedback messages and star ratings.
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.unique_users(id) ON DELETE SET NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Security: Row Level Security (RLS)
-- We enable RLS to control who can read/write data.
ALTER TABLE public.unique_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- 4. Policies: Simple anonymous access for MVP
-- Allows the client-side 'anon' key to insert data.

-- Policy for unique_users
CREATE POLICY "Allow anonymous insert for unique_users" 
ON public.unique_users FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow anonymous update for unique_users" 
ON public.unique_users FOR UPDATE 
USING (true);

-- Policy for feedback
CREATE POLICY "Allow anonymous insert for feedback" 
ON public.feedback FOR INSERT 
WITH CHECK (true);

-- Note: No SELECT policies are added for anonymous users to ensure privacy.
-- Only the Service Role (Admin) can read this data via the Supabase Dashboard.
